### ISSUE TITLE
Escape key doesn't work

### ISSUE THREAD

**Issue by dreinn** [EscolarProgramming/NVDARemotePublic#10]
it appears that escape keys is not recognized when pressed.
Do you confirm?

**Comment by EscolarProgramming** [comment]
Hello,
Do you use VoiceOver? If yes, that's an Apple limitation and I found no way to fix it. VoiceOver uses this key and doesn't send the key to my app.

**Comment by EscolarProgramming** [comment]
In the next update, there's a popup which suggest you to disable VoiceOver.
