### ISSUE TITLE
Say all not continuing to speak

### ISSUE THREAD

**Issue by a-singer** [EscolarProgramming/NVDARemotePublic#2]
Hello,

When connected to the remote server from IOS, whether VoiceOver is enabled or not, issuing the say all command will start reading but will not continue after a certain point. A short time after the command is issued and reading starts, reading will stop. I have seen this with the Android version at
https://play.google.com/store/apps/details?id=im.vortex.narwall
and it was resolved, so thought it might need to be looked into on the IOS side as something to be considered.

Thanks,

**Comment by EscolarProgramming** [comment]
Hello,
Thank you for your feedback. Unfortunately, I can't reproduce it. Can you make a file with text or something, where it doesn't work, that I can test it by my own?

**Comment by EscolarProgramming** [comment]
Already fixed (https://github.com/EscolarProgramming/NVDARemotePublic/issues/6)

**Comment by a-singer** [comment]
Hi,

I'm afraid I can't confirm that this is fixed on my end. I just tried it and, again, am not able to have say all continue after a few sentences no matter what I do. Note that, I have tried this with speech on the iPhone both enabled and disabled, that is, using the phone as a full remote device and as just a long-range wireless keyboard.
Thanks,
