### ISSUE TITLE
Speech interrupts

### ISSUE THREAD

**Issue by EscolarProgramming** [EscolarProgramming/NVDARemotePublic#6]
For some reason, the speech interrupts. For example, if I open the NVDA menu, instead of hearing preferences submenu P, I will hear only P, and as I arrow through the menu only the shortcut keys will be spoken.
https://github.com/NVDARemote/NVDARemote/issues/169#issuecomment-847225731

This happens to me as well, it may be how the speech is being sent to text to speech, or VoiceOver, as I have the problem on both. However, if I read a line of text in a file, I do not have this issue, I only have it when reading menues, shortcuts, task bar items, anything where I suspect the speech may be sending data in a different manner than it otherwise would while reading text, perhaps with newlines that cause interruptions in reading on iOS, don't know about Android for this issue.
https://github.com/NVDARemote/NVDARemote/issues/169#issuecomment-847227931

**Comment by EscolarProgramming** [comment]
Hello @alekssamos and @tech10
Thank you for your feedback. Unfortunately, I can't reproduce it, all menues work fine. Can you please tell me your NVDARemote version?

**Comment by tech10** [comment]
@EscolarProgramming
I am using NVDARemote 2.3.1, an unofficial build that I created, pulled from the master branch of the GitHub repository, but 2.3 should be mostly identical to this version, so far as I am aware. You can download my build [here](https://www.vrnw.org/nvda/remote-2.3.1.nvda-addon) if you would like to test it. I am using NVDA 2020.4.

I notice the speech interrupts when I use the task bar, attempt to read shortcuts on a desktop, read links in a web browser, etc. The speech interrupts occur with VoiceOver and TTS options, neither seems better than another.

To accomplish this, I am not controlling the remote computer from the iOS device itself, though if I did, I imagine the results would be similar. I am instead controlling the remote computer from another system that I had connected at the time. Even so, the speech interrupts still shouldn't occur in this case.

If I can help you in any other way, please let me know, and thanks for the development of this program, I could see it being quite useful.

**Comment by nidza07** [comment]
Hello,
I originally reported this over on Twitter. I can reproduce this using the official NVDA remote client, version 2.3, and I am controlling the computer via iiOS device, though the same happens if I try just using my computer normally and listen to it via iOS. However, if I use NVDA 2019.2.1, the latest available Python 2 version with it's compatible remote addon, this issue does not happen. Speech still sometimes interrupts, but not nearly as often, and lists or menus can be navigated normally.
Thanks for your work.

**Comment by EscolarProgramming** [comment]
Hello,
In the next 15 minutes, there will be a new version published. Can you please check, if the problem is solved?

**Comment by nidza07** [comment]
Hello,
thank you very much. I can confirm the issue is fixed for me in the latest version.

**Comment by EscolarProgramming** [comment]
That's nice to hear! Then I'll close the issue.
